export const TALENT_DOMAINS = [
  {
    id: "data-center",
    label: "Data Center",
    icon: "🏢",
    defaultRole: "Critical Facilities Engineer",
    roles: [
      "Critical Facilities Engineer",
      "Data Center Engineer",
      "Electrical Engineer",
      "Mechanical Engineer",
      "Facilities Manager",
      "Commissioning Engineer",
      "Power Engineer",
      "BMS / Controls Engineer",
    ],
    preview: {
      targetCompanies: ["AWS", "Microsoft", "Google", "Meta", "Equinix", "Digital Realty"],
      coreSkills: ["UPS", "EPMS", "Switchgear", "Generator Systems"],
      mappedSkills: ["UPS", "EPMS", "Generator Systems"],
      certifications: ["ATD", "CDCS", "CDCP"],
      conferences: ["Data Centre World", "DCD Connect"],
      notes: "Technical talent intelligence for critical facilities, electrical, mechanical, controls, commissioning and data center operations hiring.",
    },
  },
  {
    id: "ai-ml",
    label: "AI/ML",
    icon: "🧠",
    defaultRole: "ML Engineer",
    roles: [
      "ML Engineer",
      "Research Scientist",
      "Research Engineer",
      "Applied Scientist",
      "Computer Vision Engineer",
      "NLP Engineer",
      "Generative AI Engineer",
      "Deep Learning Engineer",
    ],
    preview: {
      targetCompanies: ["OpenAI", "Anthropic", "Google DeepMind", "Meta AI", "NVIDIA", "Microsoft AI"],
      coreSkills: ["Machine Learning", "Deep Learning", "Python", "PyTorch"],
      mappedSkills: ["PyTorch", "TensorFlow", "CUDA", "Transformers", "JAX"],
      certifications: [],
      conferences: ["NeurIPS", "ICML", "ICLR", "CVPR"],
      notes: "AI/ML talent intelligence combining engineering signals with research, publication, conference and open-source evidence.",
    },
  },
  {
    id: "software",
    label: "Software",
    icon: "💻",
    defaultRole: "Software Engineer",
    roles: [
      "Software Engineer",
      "Backend Engineer",
      "Full Stack Engineer",
      "Frontend Engineer",
      "Platform Engineer",
      "Infrastructure Engineer",
      "Distributed Systems Engineer",
      "SRE",
    ],
    preview: {
      targetCompanies: ["Google", "Microsoft", "Amazon", "Meta", "Stripe", "Cloudflare"],
      coreSkills: ["Software Engineering", "Distributed Systems", "Algorithms", "System Design"],
      mappedSkills: ["Python", "Java", "Go", "C++", "TypeScript", "Kubernetes"],
      certifications: [],
      conferences: ["QCon", "KubeCon", "OSDI", "SREcon"],
      notes: "Software talent intelligence built around engineering depth, open-source contribution, systems expertise and technical communities.",
    },
  },
  {
    id: "robotics",
    label: "Robotics",
    icon: "🤖",
    defaultRole: "Robotics Engineer",
    roles: [
      "Robotics Engineer",
      "Robot Learning Engineer",
      "Robotics Research Scientist",
      "Perception Engineer",
      "Manipulation Engineer",
      "Autonomy Engineer",
      "Motion Planning Engineer",
      "Controls Engineer",
    ],
    preview: {
      targetCompanies: ["NVIDIA", "Figure", "Agility Robotics", "Skild AI", "Physical Intelligence", "Boston Dynamics"],
      coreSkills: ["Robotics", "Computer Vision", "Motion Planning", "ROS2"],
      mappedSkills: ["PyTorch", "ROS2", "OpenCV", "MoveIt", "Reinforcement Learning"],
      certifications: [],
      conferences: ["ICRA", "RSS", "CoRL", "IROS"],
      notes: "Robotics talent intelligence connecting technical graph evidence, repositories, research, publications and robotics conference activity.",
    },
  },
  {
    id: "hardware",
    label: "Hardware",
    icon: "🔬",
    defaultRole: "Hardware Engineer",
    roles: [
      "Hardware Engineer",
      "Embedded Engineer",
      "Firmware Engineer",
      "ASIC Design Engineer",
      "RTL Design Engineer",
      "Verification Engineer",
      "FPGA Engineer",
      "Semiconductor Engineer",
      "VLSI Engineer",
    ],
    preview: {
      targetCompanies: ["NVIDIA", "AMD", "Intel", "Qualcomm", "Arm", "Apple"],
      coreSkills: ["Digital Design", "Embedded Systems", "ASIC", "Semiconductor"],
      mappedSkills: ["C", "C++", "Verilog", "SystemVerilog", "FPGA", "VLSI"],
      certifications: [],
      conferences: ["ISSCC", "DAC", "Hot Chips", "DesignCon"],
      notes: "Hardware and semiconductor intelligence spanning embedded, firmware, ASIC, FPGA, VLSI, verification and silicon engineering.",
    },
  },
] as const;

export type TalentDomainId = (typeof TALENT_DOMAINS)[number]["id"];
export type TalentDomain = (typeof TALENT_DOMAINS)[number];
